//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslateCS2.Edits.Properties.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18NEdits {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18NEdits() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslateCS2.Edits.Properties.I18N.I18NEdits", typeof(I18NEdits).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string ColumnCount {
            get {
                return ResourceManager.GetString("ColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displays the count/amount/quantity of times the english value occurs/appears
        ///a little more technical: the amount of keys the english value is used for.
        /// </summary>
        public static string ColumnCountTip {
            get {
                return ResourceManager.GetString("ColumnCountTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Value.
        /// </summary>
        public static string ColumnEnglish {
            get {
                return ResourceManager.GetString("ColumnEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displays the value/text that corresponds to the key within the Key-column
        ///it&apos;s always english, cause english seems to be the &apos;leading&apos; language.
        /// </summary>
        public static string ColumnEnglishTip {
            get {
                return ResourceManager.GetString("ColumnEnglishTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string ColumnKey {
            get {
                return ResourceManager.GetString("ColumnKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displays the key used by Colossal Order.
        /// </summary>
        public static string ColumnKeyTip {
            get {
                return ResourceManager.GetString("ColumnKeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Value.
        /// </summary>
        public static string ColumnMerge {
            get {
                return ResourceManager.GetString("ColumnMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displays the value/text
        ///that corresponds to the key within the Key-column
        ///inside the localization file to merge with
        ///that is selected while creating the translation session.
        /// </summary>
        public static string ColumnMergeTip {
            get {
                return ResourceManager.GetString("ColumnMergeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string ColumnTranslation {
            get {
                return ResourceManager.GetString("ColumnTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the new value that is going to correspond to the respective key within the Key-column
        ///for each cell that is left empty, the respective value/text within the Merge Value-column gets exported.
        /// </summary>
        public static string ColumnTranslationTip {
            get {
                return ResourceManager.GetString("ColumnTranslationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation changed!.
        /// </summary>
        public static string DialogCancelCaption {
            get {
                return ResourceManager.GetString("DialogCancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Translation changed!
        ///
        ///Do you really want to cancel without saving?.
        /// </summary>
        public static string DialogCancelText {
            get {
                return ResourceManager.GetString("DialogCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete entry?.
        /// </summary>
        public static string DialogDeleteCaption {
            get {
                return ResourceManager.GetString("DialogDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this entry?.
        /// </summary>
        public static string DialogDeleteText {
            get {
                return ResourceManager.GetString("DialogDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit entry.
        /// </summary>
        public static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add entry.
        /// </summary>
        public static string DoAdd {
            get {
                return ResourceManager.GetString("DoAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string DoCancel {
            get {
                return ResourceManager.GetString("DoCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy to clipboard.
        /// </summary>
        public static string DoCopy {
            get {
                return ResourceManager.GetString("DoCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DoDelete {
            get {
                return ResourceManager.GetString("DoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string DoSave {
            get {
                return ResourceManager.GetString("DoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translate.
        /// </summary>
        public static string DoTranslate {
            get {
                return ResourceManager.GetString("DoTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key already exists!.
        /// </summary>
        public static string InputWarningKeyDuplicate {
            get {
                return ResourceManager.GetString("InputWarningKeyDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key must not be empty!.
        /// </summary>
        public static string InputWarningKeyEmpty {
            get {
                return ResourceManager.GetString("InputWarningKeyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is inconsistent. To add an indexed value the next free index &apos;{0}&apos; should be used..
        /// </summary>
        public static string InputWarningKeyIndex {
            get {
                return ResourceManager.GetString("InputWarningKeyIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key must not contain spaces!.
        /// </summary>
        public static string InputWarningSpaces {
            get {
                return ResourceManager.GetString("InputWarningSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation must not be empty!.
        /// </summary>
        public static string InputWarningTranslationEmpty {
            get {
                return ResourceManager.GetString("InputWarningTranslationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to something went wrong.
        /// </summary>
        public static string MessageSomethingWentWrong {
            get {
                return ResourceManager.GetString("MessageSomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translating text.
        /// </summary>
        public static string MessageTranslating {
            get {
                return ResourceManager.GetString("MessageTranslating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to into.
        /// </summary>
        public static string StringTranslateInto {
            get {
                return ResourceManager.GetString("StringTranslateInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translate with.
        /// </summary>
        public static string StringTranslateWith {
            get {
                return ResourceManager.GetString("StringTranslateWith", resourceCulture);
            }
        }
    }
}
