using System.Collections.ObjectModel;

namespace TranslateCS2.Core.Services.Filters;
public interface IFiltersService {
    ILocalizationKeyFilter GetFilterNone();
    ObservableCollection<ILocalizationKeyFilter> GetFiltersCustom();
    ObservableCollection<ILocalizationKeyFilter> GetFiltersAutogenerated();
}
