using System.Collections.Generic;

namespace TranslateCS2.Core.Services.Filters;
public interface IFiltersService {
    ILocalizationKeyFilter GetFilterNone();
    IList<ILocalizationKeyFilter> GetFiltersCustom();
    IList<ILocalizationKeyFilter> GetFiltersAutogenerated();
}
