//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslateCS2.Core.Properties.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18NSessions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18NSessions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslateCS2.Core.Properties.I18N.I18NSessions", typeof(I18NSessions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CurrentSessionID {
            get {
                return ResourceManager.GetString("CurrentSessionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last edited.
        /// </summary>
        public static string CurrentSessionLastEdited {
            get {
                return ResourceManager.GetString("CurrentSessionLastEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locale name in english.
        /// </summary>
        public static string CurrentSessionLocaleNameEN {
            get {
                return ResourceManager.GetString("CurrentSessionLocaleNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locale name localized.
        /// </summary>
        public static string CurrentSessionLocaleNameLocalized {
            get {
                return ResourceManager.GetString("CurrentSessionLocaleNameLocalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file to merge.
        /// </summary>
        public static string CurrentSessionMerge {
            get {
                return ResourceManager.GetString("CurrentSessionMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CurrentSessionName {
            get {
                return ResourceManager.GetString("CurrentSessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file to overwrite.
        /// </summary>
        public static string CurrentSessionOverwrite {
            get {
                return ResourceManager.GetString("CurrentSessionOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started.
        /// </summary>
        public static string CurrentSessionStarted {
            get {
                return ResourceManager.GetString("CurrentSessionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization file to overwrite must be a different ones than the ones you want to merge with!.
        /// </summary>
        public static string InputOverwriteFileWarningDifferentMergeFile {
            get {
                return ResourceManager.GetString("InputOverwriteFileWarningDifferentMergeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a localization file to overwrite!.
        /// </summary>
        public static string InputOverwriteFileWarningEmpty {
            get {
                return ResourceManager.GetString("InputOverwriteFileWarningEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization file to overwrite must be a different ones than.
        /// </summary>
        public static string InputOverwriteFileWarningOthersThan {
            get {
                return ResourceManager.GetString("InputOverwriteFileWarningOthersThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should only consist of characters, lower or uppercase, from a - z!.
        /// </summary>
        public static string InputWarningConsistOfCharacters {
            get {
                return ResourceManager.GetString("InputWarningConsistOfCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be emty or whitespaces!.
        /// </summary>
        public static string InputWarningNotEmptyOrWhitespace {
            get {
                return ResourceManager.GetString("InputWarningNotEmptyOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current Session.
        /// </summary>
        public static string StringCurrentSession {
            get {
                return ResourceManager.GetString("StringCurrentSession", resourceCulture);
            }
        }
    }
}
