//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslateCS2.Core.Properties.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18NGlobal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18NGlobal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslateCS2.Core.Properties.I18N.I18NGlobal", typeof(I18NGlobal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodetection of &apos;{0}&apos;.
        /// </summary>
        public static string ManualPathSelectorInformationCaption {
            get {
                return ResourceManager.GetString("ManualPathSelectorInformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; directory could not be detected automatically.
        ///
        ///Please navigate to your
        ///
        ///&apos;Cities: Skylines II&apos;-Installation
        ///
        ///and select the &apos;{0}&apos; directory
        ///
        ///within the following dialog..
        /// </summary>
        public static string ManualPathSelectorInformationText {
            get {
                return ResourceManager.GetString("ManualPathSelectorInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong directory selected.
        /// </summary>
        public static string ManualPathSelectorNotOkCaption {
            get {
                return ResourceManager.GetString("ManualPathSelectorNotOkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected directory
        ///
        ///does not seem to be
        ///
        ///the required &apos;{0}&apos; directory.
        ///
        ///
        ///Please navigate to your
        ///
        ///&apos;Cities: Skylines II&apos;-Installation
        ///
        ///and select the &apos;{0}&apos; directory..
        /// </summary>
        public static string ManualPathSelectorNotOkText {
            get {
                return ResourceManager.GetString("ManualPathSelectorNotOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate your &apos;Cities: Skylines II&apos;-Installation and select the &apos;{0}&apos; directory.
        /// </summary>
        public static string ManualPathSelectorSelectTitle {
            get {
                return ResourceManager.GetString("ManualPathSelectorSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App can not be used.
        ///Please take a look at &quot;Limitations&quot;.
        ///If something went wrong with the database, try to restart this app..
        /// </summary>
        public static string MessageAppUnusable {
            get {
                return ResourceManager.GetString("MessageAppUnusable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backup database.
        /// </summary>
        public static string MessageDatabaseBackUp {
            get {
                return ResourceManager.GetString("MessageDatabaseBackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to something went wrong with the database - app should be restarted.
        /// </summary>
        public static string MessageDatabaseError {
            get {
                return ResourceManager.GetString("MessageDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no target language selected.
        /// </summary>
        public static string MessageNoTargetLanguageSelected {
            get {
                return ResourceManager.GetString("MessageNoTargetLanguageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no translators available.
        /// </summary>
        public static string MessageNoTranslators {
            get {
                return ResourceManager.GetString("MessageNoTranslators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no translator selected.
        /// </summary>
        public static string MessageNoTranslatorSelected {
            get {
                return ResourceManager.GetString("MessageNoTranslatorSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restart this App.
        /// </summary>
        public static string RestartHelperErrorCaption {
            get {
                return ResourceManager.GetString("RestartHelperErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restart this App.
        ///Please try to restart it manually.
        ///If the error still occurs,
        ///please feel free to open an Issue on GitHub..
        /// </summary>
        public static string RestartHelperErrorText {
            get {
                return ResourceManager.GetString("RestartHelperErrorText", resourceCulture);
            }
        }
    }
}
