using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Ribbon;
using System.Windows.Shapes;

using Prism.Ioc;
using Prism.Services.Dialogs;

using TranslateCS2.Core.Configurations.Views;
using TranslateCS2.Core.Helpers;
using TranslateCS2.Core.Helpers.Ribbons;
using TranslateCS2.Core.Models.Localizations;
using TranslateCS2.Core.Properties;
using TranslateCS2.Core.Properties.I18N;
using TranslateCS2.Core.Services.Filters;
using TranslateCS2.Core.Sessions;
using TranslateCS2.Edits.ViewModels.Dialogs;

namespace TranslateCS2.Edits.ViewModels;

internal class EditDefaultViewModel : AEditViewModel<EditDefaultViewModel> {
    private readonly IFiltersService filtersService;
    private ILocalizationKeyFilter selectedFilter;

    public ObservableCollection<ILocalizationKeyFilter> FiltersCustom { get; private set; }
    public ObservableCollection<ILocalizationKeyFilter> FiltersAutogenerated { get; private set; }
    public EditDefaultViewModel(IContainerProvider containerProvider,
                                IViewConfigurations viewConfigurations,
                                ITranslationSessionManager translationSessionManager,
                                IFiltersService filtersService,
                                IDialogService dialogService) : base(containerProvider,
                                                                     viewConfigurations,
                                                                     translationSessionManager,
                                                                     dialogService) {
        this.filtersService = filtersService;
        this.FiltersCustom = this.filtersService.GetFiltersCustom();
        this.FiltersAutogenerated = this.filtersService.GetFiltersAutogenerated();
        this.selectedFilter = this.filtersService.GetFilterNone();
        this.AddToolsGroup();
        this.AddCountGroup();
        this.AddAffectedSessionGroup();
        this.TextSearchContext.Columns.AddRange(this.columnsSearchAble);
        this.TextSearchContext.OnSearch += this.RefreshViewList;
    }

    protected override void CellEditEndingCommandAction(DataGridCellEditEndingEventArgs args) {
        if (args.Row.Item is not IAppLocFileEntry edited) {
            return;
        }
        if (args.EditingElement is not TextBox textBox) {
            return;
        }
        this.Save(textBox.Text.Trim(), edited);
    }

    protected override void Save(string? translation, IAppLocFileEntry edited) {
        if (this.CurrentSession is null) {
            return;
        }
        if (edited.KeyOrigin is not null
            && edited.KeyOrigin != edited.Key.Key) {
            // key has changed
            // set translation to null to delete from database
            IEnumerable<KeyValuePair<string, IAppLocFileEntry>> existings = this.CurrentSession.Localizations.Where(item => item.Key == edited.KeyOrigin);
            if (existings.Any()) {
                KeyValuePair<string, IAppLocFileEntry> existing = existings.First();
                existing.Value.Translation = null;
                this.SessionManager.SaveCurrentTranslationSessionsTranslations();
                this.CurrentSession.Localizations.Remove(existing);
            }
        }
        KeyValuePair<string, IAppLocFileEntry> editedKeyValuePair = new KeyValuePair<string, IAppLocFileEntry>(edited.Key.Key, edited);
        if (!this.CurrentSession.Localizations.Select(item => item.Key).Contains(edited.Key.Key)) {
            this.CurrentSession.Localizations.Add(editedKeyValuePair);
        }
        base.SetNewValue(this.CurrentSession.Localizations, translation, edited);
        this.SessionManager.SaveCurrentTranslationSessionsTranslations();
        if (this.SessionManager.HasDatabaseError) {
            // see xaml-code
        }
    }

    protected override void RefreshViewList() {
        this.Mapping.Clear();
        if (this.CurrentSession is null
            || this.CurrentSession.Localizations is null) {
            return;
        }
        foreach (KeyValuePair<string, IAppLocFileEntry> entry in this.CurrentSession.Localizations) {
            if (this.selectedFilter.Matches(entry.Value)) {
                bool add = false;
                if (this.OnlyTranslated
                    && !this.HideTranslated
                    && entry.Value.IsTranslated) {
                    add = true;
                } else if (!this.OnlyTranslated
                           && !this.HideTranslated) {
                    add = true;
                } else if (this.HideTranslated
                           && !this.OnlyTranslated
                           && !entry.Value.IsTranslated) {
                    add = true;
                }
                if (!add) {
                    continue;
                }
                if (!this.TextSearchContext.IsTextSearchMatch(entry.Value)) {
                    continue;
                }
                this.Mapping.Add(entry.Value);
            }
        }
        base.RefreshViewList();
    }

    protected override IEnumerable<object> CreateToolsGroupItems() {
        IList<object> items = [];
        {
            RibbonButton button = RibbonHelper.CreateRibbonButton(Properties.I18N.I18NEdits.DoAdd,
                                                                  ImageResources.add,
                                                                  this.AddEntry);
            items.Add(button);
        }
        {
            Rectangle rectangle = RibbonHelper.CreateInGroupSeparator();
            items.Add(rectangle);
        }
        {
            RibbonComboBoxConfig config = new RibbonComboBoxConfig(I18NRibbon.FilterKeys) {
                OnSelectionChanged = this.FilterChanged,
                SelectedItem = this.selectedFilter,
                DisplayMemberPath = nameof(ILocalizationKeyFilter.Name)
            };
            config.ItemsList.Add(new RibbonComboBoxItems(new List<ILocalizationKeyFilter>([this.selectedFilter])));
            config.ItemsList.Add(new RibbonComboBoxItems(this.FiltersCustom) { SeparatorLabel = I18NRibbon.FiltersCustomLabel });
            config.ItemsList.Add(new RibbonComboBoxItems(this.FiltersAutogenerated) { SeparatorLabel = I18NRibbon.FiltersAutogeneratedLabel });
            items.Add(RibbonHelper.CreateComboBox(config));
        }
        return items;
    }

    private void FilterChanged(object sender, RoutedPropertyChangedEventArgs<object> e) {
        if (e.NewValue is ILocalizationKeyFilter newValue) {
            this.selectedFilter = newValue;
            this.RefreshViewList();
        }
    }

    private void AddEntry(object sender, RoutedEventArgs e) {
        IAppLocFileEntry newEntry = AppLocFileEntryFactory.CreateEmpty();
        IDialogParameters parameters = new DialogParameters {
            { nameof(IAppLocFileEntry), newEntry },
            { nameof(EditEntryLargeViewModel.IsCount), false }
        };
        this.OpenEditEntryLarge(parameters);
    }
}
