//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslateCS2.ExImport.Properties.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18NExport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18NExport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslateCS2.ExImport.Properties.I18N.I18NExport", typeof(I18NExport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string DialogText {
            get {
                return ResourceManager.GetString("DialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export translation to JSON.
        /// </summary>
        public static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DialogWarningCaption {
            get {
                return ResourceManager.GetString("DialogWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a .json-file..
        /// </summary>
        public static string DialogWarningText {
            get {
                return ResourceManager.GetString("DialogWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export.
        /// </summary>
        public static string DoExport {
            get {
                return ResourceManager.GetString("DoExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select file.
        /// </summary>
        public static string DoSelectFile {
            get {
                return ResourceManager.GetString("DoSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exporting.
        /// </summary>
        public static string MessageDo {
            get {
                return ResourceManager.GetString("MessageDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export failed.
        /// </summary>
        public static string MessageFail {
            get {
                return ResourceManager.GetString("MessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preparing translation for export.
        /// </summary>
        public static string MessagePrepareDo {
            get {
                return ResourceManager.GetString("MessagePrepareDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translation is ready to export.
        /// </summary>
        public static string MessagePrepareSuccess {
            get {
                return ResourceManager.GetString("MessagePrepareSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exported.
        /// </summary>
        public static string MessageSuccess {
            get {
                return ResourceManager.GetString("MessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace existing localization based on session-properties.
        /// </summary>
        public static string ToolTipExportFormatDirectOverwrite {
            get {
                return ResourceManager.GetString("ToolTipExportFormatDirectOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export to use with I18NEverywhere.
        /// </summary>
        public static string ToolTipExportFormatI18NEverywhere {
            get {
                return ResourceManager.GetString("ToolTipExportFormatI18NEverywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export as json to share with others.
        /// </summary>
        public static string ToolTipExportFormatJSON {
            get {
                return ResourceManager.GetString("ToolTipExportFormatJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export to use with TranslateCS2.Mod.
        /// </summary>
        public static string ToolTipExportFormatTranslateCS2Mod {
            get {
                return ResourceManager.GetString("ToolTipExportFormatTranslateCS2Mod", resourceCulture);
            }
        }
    }
}
