//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslateCS2.ExImport.Properties.I18N {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18NImport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18NImport() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslateCS2.ExImport.Properties.I18N.I18NImport", typeof(I18NImport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        public static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hide equal translations ähnelt.
        /// </summary>
        public static string CheckBoxHideEqual {
            get {
                return ResourceManager.GetString("CheckBoxHideEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Existing Translation ähnelt.
        /// </summary>
        public static string ColumnExisting {
            get {
                return ResourceManager.GetString("ColumnExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die displays the current translation that is assigned to the respective key ähnelt.
        /// </summary>
        public static string ColumnExistingTip {
            get {
                return ResourceManager.GetString("ColumnExistingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key ähnelt.
        /// </summary>
        public static string ColumnKey {
            get {
                return ResourceManager.GetString("ColumnKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die displays the key used by Colossal Order ähnelt.
        /// </summary>
        public static string ColumnKeyTip {
            get {
                return ResourceManager.GetString("ColumnKeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read Translation ähnelt.
        /// </summary>
        public static string ColumnRead {
            get {
                return ResourceManager.GetString("ColumnRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die displays the translation from the read json-file that is assigned to the respective key ähnelt.
        /// </summary>
        public static string ColumnReadTip {
            get {
                return ResourceManager.GetString("ColumnReadTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import-Comparison-Window ähnelt.
        /// </summary>
        public static string ComparisonDialogTitle {
            get {
                return ResourceManager.GetString("ComparisonDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to import into the current translation session selected within the Session(s)-Tab? ähnelt.
        /// </summary>
        public static string DialogText {
            get {
                return ResourceManager.GetString("DialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die import translation from JSON ähnelt.
        /// </summary>
        public static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string DialogWarningCaption {
            get {
                return ResourceManager.GetString("DialogWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a .json-file. ähnelt.
        /// </summary>
        public static string DialogWarningText {
            get {
                return ResourceManager.GetString("DialogWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die import
        ///into
        ///database ähnelt.
        /// </summary>
        public static string DoImport {
            get {
                return ResourceManager.GetString("DoImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die compare
        ///in new
        ///window ähnelt.
        /// </summary>
        public static string DoOpenCompare {
            get {
                return ResourceManager.GetString("DoOpenCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die read
        ///selected
        ///file ähnelt.
        /// </summary>
        public static string DoRead {
            get {
                return ResourceManager.GetString("DoRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die select
        ///file ähnelt.
        /// </summary>
        public static string DoSelectFile {
            get {
                return ResourceManager.GetString("DoSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die import translations into database ähnelt.
        /// </summary>
        public static string MessageImport {
            get {
                return ResourceManager.GetString("MessageImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die translations successfully imported into database ähnelt.
        /// </summary>
        public static string MessageImportSuccess {
            get {
                return ResourceManager.GetString("MessageImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die read translations to review and to select an import-mode ähnelt.
        /// </summary>
        public static string MessageRead {
            get {
                return ResourceManager.GetString("MessageRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die selected file cannot be read ähnelt.
        /// </summary>
        public static string MessageReadFail {
            get {
                return ResourceManager.GetString("MessageReadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die translations read to review and to select an import-mode ähnelt.
        /// </summary>
        public static string MessageReadSuccess {
            get {
                return ResourceManager.GetString("MessageReadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die warning: filters do not affect/exclude translations to/from import. they just ease comparison. ähnelt.
        /// </summary>
        public static string WarningFilters {
            get {
                return ResourceManager.GetString("WarningFilters", resourceCulture);
            }
        }
    }
}
