//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslateCS2.ExImport.Properties.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18NExport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18NExport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslateCS2.ExImport.Properties.I18N.I18NExport", typeof(I18NExport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changelog.
        /// </summary>
        public static string ButtonLabelModChangeLog {
            get {
                return ResourceManager.GetString("ButtonLabelModChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to readme.
        /// </summary>
        public static string ButtonLabelModReadMe {
            get {
                return ResourceManager.GetString("ButtonLabelModReadMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TranslateCS2.Mod.
        /// </summary>
        public static string CaptionAdditionalInformation {
            get {
                return ResourceManager.GetString("CaptionAdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string DialogText {
            get {
                return ResourceManager.GetString("DialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export translation to JSON.
        /// </summary>
        public static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DialogWarningCaption {
            get {
                return ResourceManager.GetString("DialogWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a .json-file..
        /// </summary>
        public static string DialogWarningText {
            get {
                return ResourceManager.GetString("DialogWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add key.
        /// </summary>
        public static string DoAddKey {
            get {
                return ResourceManager.GetString("DoAddKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add merge-values.
        /// </summary>
        public static string DoAddMergeValues {
            get {
                return ResourceManager.GetString("DoAddMergeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export.
        /// </summary>
        public static string DoExport {
            get {
                return ResourceManager.GetString("DoExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select file.
        /// </summary>
        public static string DoSelectFile {
            get {
                return ResourceManager.GetString("DoSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TranslateCS2.Mod.
        /// </summary>
        public static string HeaderMod {
            get {
                return ResourceManager.GetString("HeaderMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exporting.
        /// </summary>
        public static string MessageDo {
            get {
                return ResourceManager.GetString("MessageDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export failed.
        /// </summary>
        public static string MessageFail {
            get {
                return ResourceManager.GetString("MessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preparing translation for export.
        /// </summary>
        public static string MessagePrepareDo {
            get {
                return ResourceManager.GetString("MessagePrepareDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translation is ready to export.
        /// </summary>
        public static string MessagePrepareSuccess {
            get {
                return ResourceManager.GetString("MessagePrepareSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exported.
        /// </summary>
        public static string MessageSuccess {
            get {
                return ResourceManager.GetString("MessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adds a Key-Value-Pair that controls the displayed language-name within the game
        ///
        ///does not affect built in languages where flavors are &apos;added&apos;.
        /// </summary>
        public static string ToolTipExportAddKey {
            get {
                return ResourceManager.GetString("ToolTipExportAddKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add merge-values checked:
        ///for entries, that do not have a translation, texts/translations get exported from the selected merge-file
        ///
        ///
        ///add merge-values unchecked:
        ///only entries that have a translation get exported
        ///&apos;missing&apos; entries are supplemented within the game with the fallbacklanguage &apos;en-US&apos;.
        /// </summary>
        public static string ToolTipExportAddMergeValues {
            get {
                return ResourceManager.GetString("ToolTipExportAddMergeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace existing localization based on session-properties
        ///
        ///this export method overwrites the selected file to overwrite within the game-folder.
        /// </summary>
        public static string ToolTipExportFormatDirectOverwrite {
            get {
                return ResourceManager.GetString("ToolTipExportFormatDirectOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export as json to share with others.
        /// </summary>
        public static string ToolTipExportFormatJSON {
            get {
                return ResourceManager.GetString("ToolTipExportFormatJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filename proposals based on the current sessions english name
        ///
        ///selected ones is preassigned within the save file dialog
        ///
        ///can not be saved to database.
        /// </summary>
        public static string ToolTipExportGatheredFileName {
            get {
                return ResourceManager.GetString("ToolTipExportGatheredFileName", resourceCulture);
            }
        }
    }
}
