//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslateCS2.Assets.i18n {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslateCS2.Assets.i18n.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is a Test ähnelt.
        /// </summary>
        internal static string MessageAppUnusableWarning {
            get {
                return ResourceManager.GetString("MessageAppUnusableWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Should only consist of characters, lower or uppercase, from a - z! ähnelt.
        /// </summary>
        internal static string MessageConsistOfCharacters {
            get {
                return ResourceManager.GetString("MessageConsistOfCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Localization file to overwrite must be a different ones than the ones you want to merge with! ähnelt.
        /// </summary>
        internal static string MessageLocalizationFileOverwriteDifferentMerge {
            get {
                return ResourceManager.GetString("MessageLocalizationFileOverwriteDifferentMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Localization file to overwrite must be a different ones than ähnelt.
        /// </summary>
        internal static string MessageLocalizationFileOverwriteOthersThan {
            get {
                return ResourceManager.GetString("MessageLocalizationFileOverwriteOthersThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die May not be emty or whitespaces! ähnelt.
        /// </summary>
        internal static string MessageNotEmptyOrWhitespace {
            get {
                return ResourceManager.GetString("MessageNotEmptyOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die preparing translation for export ähnelt.
        /// </summary>
        internal static string MessagePreparingTranslationExport {
            get {
                return ResourceManager.GetString("MessagePreparingTranslationExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a localization file to overwrite! ähnelt.
        /// </summary>
        internal static string MessageSelectLocalizationFileOverwrite {
            get {
                return ResourceManager.GetString("MessageSelectLocalizationFileOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die translation is ready to export ähnelt.
        /// </summary>
        internal static string MessageTranslationReadyExport {
            get {
                return ResourceManager.GetString("MessageTranslationReadyExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die localename in english ähnelt.
        /// </summary>
        internal static string MessageTranslationSessionLocaleEnglish {
            get {
                return ResourceManager.GetString("MessageTranslationSessionLocaleEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die localename in your language ähnelt.
        /// </summary>
        internal static string MessageTranslationSessionLocaleLocalized {
            get {
                return ResourceManager.GetString("MessageTranslationSessionLocaleLocalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die if you only want to change some translations, tanslations within this file and yours are going to be merged; or if you want to create a new translation e.g. based on english, you&apos;ll get a mixed translation file ähnelt.
        /// </summary>
        internal static string MessageTranslationSessionMergeFile {
            get {
                return ResourceManager.GetString("MessageTranslationSessionMergeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die a name for your translation session ähnelt.
        /// </summary>
        internal static string MessageTranslationSessionName {
            get {
                return ResourceManager.GetString("MessageTranslationSessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die the localization file you want to sacrifice/overwrite. should be another language than english and the ones you want to merge; a language that you are unable to read/speak ähnelt.
        /// </summary>
        internal static string MessageTranslationSessionOverwriteFile {
            get {
                return ResourceManager.GetString("MessageTranslationSessionOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die under construction ähnelt.
        /// </summary>
        internal static string MessageUnderConstruction {
            get {
                return ResourceManager.GetString("MessageUnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        /// </summary>
        internal static string QuestionAreYouSure {
            get {
                return ResourceManager.GetString("QuestionAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die autodetected Cities: Skylines 2 - Installation Directory ähnelt.
        /// </summary>
        internal static string StringAutoDetectedInstallationDirectory {
            get {
                return ResourceManager.GetString("StringAutoDetectedInstallationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die autodetected .loc-files ähnelt.
        /// </summary>
        internal static string StringAutoDetectedLocFiles {
            get {
                return ResourceManager.GetString("StringAutoDetectedLocFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Count ähnelt.
        /// </summary>
        internal static string StringCountCap {
            get {
                return ResourceManager.GetString("StringCountCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die create ähnelt.
        /// </summary>
        internal static string StringCreate {
            get {
                return ResourceManager.GetString("StringCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Credits ähnelt.
        /// </summary>
        internal static string StringCreditsCaps {
            get {
                return ResourceManager.GetString("StringCreditsCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die edit ähnelt.
        /// </summary>
        internal static string StringEdit {
            get {
                return ResourceManager.GetString("StringEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit by occurances ähnelt.
        /// </summary>
        internal static string StringEditByOccurancesCap {
            get {
                return ResourceManager.GetString("StringEditByOccurancesCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string StringEditCap {
            get {
                return ResourceManager.GetString("StringEditCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EnglishValue ähnelt.
        /// </summary>
        internal static string StringEnglishValueCap {
            get {
                return ResourceManager.GetString("StringEnglishValueCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die export ähnelt.
        /// </summary>
        internal static string StringExport {
            get {
                return ResourceManager.GetString("StringExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        /// </summary>
        internal static string StringExportCap {
            get {
                return ResourceManager.GetString("StringExportCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die exported ähnelt.
        /// </summary>
        internal static string StringExported {
            get {
                return ResourceManager.GetString("StringExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die exporting ähnelt.
        /// </summary>
        internal static string StringExporting {
            get {
                return ResourceManager.GetString("StringExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die export translation ähnelt.
        /// </summary>
        internal static string StringExportTranslation {
            get {
                return ResourceManager.GetString("StringExportTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die filter keys ähnelt.
        /// </summary>
        internal static string StringFilterKeys {
            get {
                return ResourceManager.GetString("StringFilterKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hide translated ähnelt.
        /// </summary>
        internal static string StringHideTranslated {
            get {
                return ResourceManager.GetString("StringHideTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die in ähnelt.
        /// </summary>
        internal static string StringIn {
            get {
                return ResourceManager.GetString("StringIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Key ähnelt.
        /// </summary>
        internal static string StringKeyCap {
            get {
                return ResourceManager.GetString("StringKeyCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MergeValue ähnelt.
        /// </summary>
        internal static string StringMergeValueCap {
            get {
                return ResourceManager.GetString("StringMergeValueCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die name ähnelt.
        /// </summary>
        internal static string StringName {
            get {
                return ResourceManager.GetString("StringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Navigation ähnelt.
        /// </summary>
        internal static string StringNavigationCap {
            get {
                return ResourceManager.GetString("StringNavigationCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new ähnelt.
        /// </summary>
        internal static string StringNew {
            get {
                return ResourceManager.GetString("StringNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die search ähnelt.
        /// </summary>
        internal static string StringSearch {
            get {
                return ResourceManager.GetString("StringSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die search for ähnelt.
        /// </summary>
        internal static string StringSearchFor {
            get {
                return ResourceManager.GetString("StringSearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die selected ähnelt.
        /// </summary>
        internal static string StringSelected {
            get {
                return ResourceManager.GetString("StringSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die session ähnelt.
        /// </summary>
        internal static string StringSession {
            get {
                return ResourceManager.GetString("StringSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Session Management ähnelt.
        /// </summary>
        internal static string StringSessionManagementCap {
            get {
                return ResourceManager.GetString("StringSessionManagementCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Session(s) ähnelt.
        /// </summary>
        internal static string StringSessionsCap {
            get {
                return ResourceManager.GetString("StringSessionsCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string StringSettingsCap {
            get {
                return ResourceManager.GetString("StringSettingsCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die only show translated ähnelt.
        /// </summary>
        internal static string StringShowOnlyTranslated {
            get {
                return ResourceManager.GetString("StringShowOnlyTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string StringStartCap {
            get {
                return ResourceManager.GetString("StringStartCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        /// </summary>
        internal static string StringToolsCap {
            get {
                return ResourceManager.GetString("StringToolsCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translation ähnelt.
        /// </summary>
        internal static string StringTranslationCap {
            get {
                return ResourceManager.GetString("StringTranslationCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die localename in english ähnelt.
        /// </summary>
        internal static string StringTranslationSessionLocaleEnglish {
            get {
                return ResourceManager.GetString("StringTranslationSessionLocaleEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die localename localized ähnelt.
        /// </summary>
        internal static string StringTranslationSessionLocaleLocalized {
            get {
                return ResourceManager.GetString("StringTranslationSessionLocaleLocalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die localization file to merge with ähnelt.
        /// </summary>
        internal static string StringTranslationSessionMergeFile {
            get {
                return ResourceManager.GetString("StringTranslationSessionMergeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die localization file to overwrite ähnelt.
        /// </summary>
        internal static string StringTranslationSessionOverwriteFile {
            get {
                return ResourceManager.GetString("StringTranslationSessionOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die translation sessions (selected ones is current) ähnelt.
        /// </summary>
        internal static string StringTranslationSessions {
            get {
                return ResourceManager.GetString("StringTranslationSessions", resourceCulture);
            }
        }
    }
}
