using System.IO;

using TranslateCS2.Core.Configurations;

namespace TranslateCS2.Core.Services.InstallPaths;
// TODO: AAA-3: requires an InstallPathSelector that is displayed at startup if no installdir could be detected
// TODO: AAA-4: after the user selected the (correct) installdir manually, the location should be saved to a file
/// <see cref="AppConfigurationManager.CitiesLocation"/>
// TODO: AAA-5: and the app should be restarted automatically, cause three locations are affected by the InstallPathDetector:
/// 1st <see cref="TranslateCS2.Edits.ViewModels.EditDefaultViewModel.FiltersAutogenerated"/>
// that are used within the RibbonComboBoxItems
/// 2nd <see cref="TranslateCS2.Edits.ViewModels.EditDefaultViewModel.CreateToolsGroupItems"/>
/// 3rd <see cref="TranslateCS2.Sessions.Views.SessionManagement"/>
// TODO: AAA-6: so it should be much easier to restart the app automatically, than to implement update-logic...
internal class PathDetectorManual : APathDetector {

    public PathDetectorManual() { }

    public override bool Detect() {
        try {
            if (File.Exists(AppConfigurationManager.CitiesLocation)) {
                this.InstallPath = File.ReadAllLines(AppConfigurationManager.CitiesLocation)[0];
                return base.Detect();
            }
        } catch { }
        return false;
    }
}
