//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslateCS2.Properties.I18N {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18NSessions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18NSessions() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslateCS2.Properties.I18N.I18NSessions", typeof(I18NSessions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Session Management ähnelt.
        /// </summary>
        public static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die cancel ähnelt.
        /// </summary>
        public static string DoCancel {
            get {
                return ResourceManager.GetString("DoCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die create
        ///new
        ///session ähnelt.
        /// </summary>
        public static string DoCreate {
            get {
                return ResourceManager.GetString("DoCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die edit
        ///selected
        ///session ähnelt.
        /// </summary>
        public static string DoEdit {
            get {
                return ResourceManager.GetString("DoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die save ähnelt.
        /// </summary>
        public static string DoSave {
            get {
                return ResourceManager.GetString("DoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die localename in english ähnelt.
        /// </summary>
        public static string InputLocaleEnglish {
            get {
                return ResourceManager.GetString("InputLocaleEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die localename in english ähnelt.
        /// </summary>
        public static string InputLocaleEnglishTip {
            get {
                return ResourceManager.GetString("InputLocaleEnglishTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die localename localized ähnelt.
        /// </summary>
        public static string InputLocaleLocalized {
            get {
                return ResourceManager.GetString("InputLocaleLocalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die localename in your language;
        ///be careful;
        ///unknown restrictions/limitations ähnelt.
        /// </summary>
        public static string InputLocaleLocalizedTip {
            get {
                return ResourceManager.GetString("InputLocaleLocalizedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die localization file to merge with ähnelt.
        /// </summary>
        public static string InputMergeFile {
            get {
                return ResourceManager.GetString("InputMergeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die if you only want to change some translations,
        ///tanslations within this file and yours are going to be merged;
        ///or if you want to create a new translation e.g. based on english,
        ///you&apos;ll get a mixed translation file ähnelt.
        /// </summary>
        public static string InputMergeFileTip {
            get {
                return ResourceManager.GetString("InputMergeFileTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die name ähnelt.
        /// </summary>
        public static string InputName {
            get {
                return ResourceManager.GetString("InputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die a name for your translation session ähnelt.
        /// </summary>
        public static string InputNameTip {
            get {
                return ResourceManager.GetString("InputNameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die localization file to overwrite ähnelt.
        /// </summary>
        public static string InputOverwriteFile {
            get {
                return ResourceManager.GetString("InputOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die the localization file you want to sacrifice/overwrite.
        ///should be another language than english
        ///and the ones you want to merge;
        ///a language that you are unable to read/speak;
        ///so you always have an ingame-fallback without the need to verify your installation files ähnelt.
        /// </summary>
        public static string InputOverwriteFileTip {
            get {
                return ResourceManager.GetString("InputOverwriteFileTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Localization file to overwrite must be a different ones than the ones you want to merge with! ähnelt.
        /// </summary>
        public static string InputOverwriteFileWarningDifferentMergeFile {
            get {
                return ResourceManager.GetString("InputOverwriteFileWarningDifferentMergeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a localization file to overwrite! ähnelt.
        /// </summary>
        public static string InputOverwriteFileWarningEmpty {
            get {
                return ResourceManager.GetString("InputOverwriteFileWarningEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Localization file to overwrite must be a different ones than ähnelt.
        /// </summary>
        public static string InputOverwriteFileWarningOthersThan {
            get {
                return ResourceManager.GetString("InputOverwriteFileWarningOthersThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die translation sessions (selected ones is current) ähnelt.
        /// </summary>
        public static string InputSelectSession {
            get {
                return ResourceManager.GetString("InputSelectSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Should only consist of characters, lower or uppercase, from a - z! ähnelt.
        /// </summary>
        public static string InputWarningConsistOfCharacters {
            get {
                return ResourceManager.GetString("InputWarningConsistOfCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Must not be emty or whitespaces! ähnelt.
        /// </summary>
        public static string InputWarningNotEmptyOrWhitespace {
            get {
                return ResourceManager.GetString("InputWarningNotEmptyOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die autodetected .loc-files ähnelt.
        /// </summary>
        public static string OutputAutoDetectedLocFiles {
            get {
                return ResourceManager.GetString("OutputAutoDetectedLocFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die autodetected Cities: Skylines 2 - Installation Directory ähnelt.
        /// </summary>
        public static string OutputInstallationDirectory {
            get {
                return ResourceManager.GetString("OutputInstallationDirectory", resourceCulture);
            }
        }
    }
}
